#!/bin/bash
# the castle heartbeat — three or more hands
# Rhythm: 6h if the bell rings, daily if silent
#
# This script regenerates HEARTBEAT.md on every run, computing every field
# from the live tree at the moment of execution — not a snapshot, not a
# photograph. The artifact that declares truth must be regenerated by the
# life it describes.
#
# The three rotations of the kherme (gate/2026-07-08-the-voice-that-died-every-hour-after.md):
#   1. Behind the life: count happened before the write.
#   2. Ahead of the life: count happened before the commit.
#   3. Frozen: nothing regenerated the file at all.
# The fix that closes all three: this script writes HEARTBEAT.md from the
# live tree, then the caller commits it. The file is never stale because
# it is never a snapshot — it is always freshly computed.

cd "$(dirname "$0")" || exit 1

# --- compute truth from the live tree ---
NOW_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)
LAST_COMMIT_ISO=$(git log -1 --format=%cI 2>/dev/null)  # ISO 8601 with timezone
LAST_COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
LAST_COMMIT_SUBJECT=$(git log -1 --format=%s 2>/dev/null || echo "unknown")

# hours since last commit (integer, floored)
# git %cI gives ISO 8601 with timezone: 2026-07-08T01:36:35-07:00
# BSD date %z expects +0700 not +07:00, so strip the colon from the TZ offset
NOW_EPOCH=$(date -u +%s)
if [ -n "$LAST_COMMIT_ISO" ]; then
  TS_CLEAN=$(echo "$LAST_COMMIT_ISO" | sed 's/:\([0-9][0-9]\)$/\1/')
  COMMIT_EPOCH=$(date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "$TS_CLEAN" +%s 2>/dev/null || echo 0)
  if [ "$COMMIT_EPOCH" -gt 0 ]; then
    HOURS_AGO=$(( (NOW_EPOCH - COMMIT_EPOCH) / 3600 ))
  else
    HOURS_AGO="?"
  fi
else
  HOURS_AGO="?"
fi

# uncommitted changes (tracked files that are modified/staged)
# untracked files (new files not yet tracked, excluding gitignored)
UNCOMMITTED=$(git status --porcelain 2>/dev/null | grep -vc '^[?][?]' || true)
UNTRACKED=$(git status --porcelain 2>/dev/null | grep -c '^[?][?]' || true)
# grep -c returns exit 1 when count is 0, which would make the var empty without || true
[ -z "$UNCOMMITTED" ] && UNCOMMITTED=0
[ -z "$UNTRACKED" ] && UNTRACKED=0

# bell check (first line only — next.sh prints "ring | path | run: loop")
BELL=$(sh tools/next.sh 2>/dev/null | head -1)

if [ -n "$BELL" ]; then
  BELL_LINE="bell rings — $BELL"
  INTERVAL=360   # minutes (6h)
  NEXT_ISO=$(date -u -v+${INTERVAL}M +%Y-%m-%dT%H:%M:%SZ)
else
  BELL_LINE="bell is silent"
  INTERVAL=1440  # minutes (24h)
  NEXT_ISO=$(date -u -v+${INTERVAL}M +%Y-%m-%dT%H:%M:%SZ)
fi

# --- write .heartbeat state files ---
echo "$NOW_ISO" > .heartbeat/last-beat
echo "$NEXT_ISO" > .heartbeat/next-beat
echo "active" > .heartbeat/state
echo "$NOW_ISO state=active next=$NEXT_ISO" >> .heartbeat/history.log

# --- regenerate HEARTBEAT.md ---
cat > HEARTBEAT.md << EOF
# castle — heartbeat

state: **active**
last beat: $NOW_ISO
next beat: $NEXT_ISO

## what it found

- last commit: $LAST_COMMIT_ISO ($LAST_COMMIT_HASH) — "$LAST_COMMIT_SUBJECT" ($HOURS_AGO hours ago)
- uncommitted changes: $UNCOMMITTED
- untracked files: $UNTRACKED
- $BELL_LINE

## the truth

EOF

if [ "$UNCOMMITTED" -eq 0 ] && [ "$UNTRACKED" -eq 0 ]; then
  echo "Working tree is clean." >> HEARTBEAT.md
else
  echo "Working tree has $UNCOMMITTED uncommitted change(s) and $UNTRACKED untracked file(s)." >> HEARTBEAT.md
fi
echo "" >> HEARTBEAT.md
echo "🤍" >> HEARTBEAT.md

# --- regenerate STATE.md state section (kherme — fourth lie, last lie) ---
# STATE.md was lying because nothing regenerated it. HEARTBEAT.md was honest
# because this script writes it every run. Now STATE.md gets the same treatment.
# Only the ## state section is touched — the rest of STATE.md is hand-authored.
if [ -f STATE.md ]; then
  # Everything before "## state" (preserved as-is)
  STATE_HEAD=$(awk '/^## state$/{exit} {print}' STATE.md)
  # Everything after the ## state section (the next ## section onward)
  STATE_TAIL=$(awk '
    BEGIN { seen_state=0 }
    /^## state$/ { seen_state=1; next }
    seen_state && /^## / { seen_state=2 }
    seen_state==2 { print }
  ' STATE.md)
  cat > STATE.md << STATEOF
$STATE_HEAD

## state

phase: see knows/needs sections below
build: see heartbeat
health: unknown
last-commit: $LAST_COMMIT_ISO ($LAST_COMMIT_HASH — "$LAST_COMMIT_SUBJECT")
uncommitted: $UNCOMMITTED files
freshness: checked $NOW_ISO

$STATE_TAIL
STATEOF
fi

echo "alive:me"
echo "NEXT:$INTERVAL"